# READ DATA INTO SCRIPT

advert <- read.csv("C:/Users/User/OneDrive/Documents/Yale-NUS/Quantitative Reasoning/Quantitative Reasoning Repository/Final Examinations/advert.csv")

head(advert)

#___________________________________________________

# Q1 (A). CREATE ONE SCATTER PLOT SHOWING RELATIONSHIP BETWEEN AGE AND NEWSPAPER SPENDING 

# create the plot
plot(NEWS ~ MEDAGE,
     data = advert,
     main = "Relationship Between Age and Newspaper Spending",
     xlab = "Median Age",
     ylab = "Newspaper Spending (in $1000USD)")

# add the line of best fit
model <- lm(NEWS ~ MEDAGE, data = advert)
abline(model, col = "red", lwd = 2)


# Q1 (B). ARE THE RESIDUALS NORMALLY DISTRIBUTED? SUPPORT YOUR ANSWER WITH PLOTS.

# plot the residuals
residuals <- residuals(model)
hist(residuals)

qqnorm(residuals)
qqline(residuals, col = "red")

# The residuals are close to normally distributed, by looking at the
# Histogram of the distribution of the residuals as well as the QQ Plots


# Q1 (C). HOW MUCH WOULD A MARKET WITH A MEDAGE OF 73 SPEND ON NEWSPAPER ADS?

Expenditure <- predict(model, newdata = data.frame(MEDAGE = 73))
Expenditure

# According to the model, a market with a median age of 73
# would spend $8.516606 thousand USD on newspaper ads

#____________________________________________________

# Q2 (A). HOW MANY THOUSANDS OF DOLLARS OF ADDITIONAL BISCUITS ARE GENERATED BY EVERY ADDITIONAL 1 THOUSAND ON TV?

TVmodel <- lm(SALES ~ TV,data = advert)
TVmodel

# Find the increase in biscuit sales by multiplying slope
slope <- TVmodel$coefficients[2]
slope

# According to the linear model, for every increase in $1000 of TV ads,
# The amount of sales increases by $-0.02977 thousand


# Q2 (B). HOW MANY THOUSANDS OF DOLLARS OF ADDITIONAL BISCUITS ARE GENERATED BY EVERY ADDITIONAL 1 THOUSAND ON RADIO?

RADmodel <- lm(SALES ~ RAD,data = advert)
RADmodel

# Find the increase in biscuit sales by multiplying slope
slope <- RADmodel$coefficients[2]
slope

# According to the linear model, for every increase in $1000 of TV ads,
# The amount of sales decreases by $-9.15 thousand


# Q2 (C). HOW MUCH OF THE VARIANCE IN BISCUIT SALES DO TV AND RADIO ACCOUNT FOR?

varianceTV <- summary(TVmodel)$r.squared * 100
varianceRAD <- summary(RADmodel)$r.squared * 100
varianceTV
varianceRAD

# The variance in biscuit sales of TV accounted for 0.00014% while
# Variance in Radio accounted for 0.749%

#___________________________________________________

# Q3 (A). CALCULATE MEAN SPENDING ON BISCUITS FOR NORTHERN AND SOUTHERN MARKETS

# for northern districts
meanN <- mean(advert$SALES[advert$AREA == 'N'])
meanN

# for southern districts
meanS <- mean(advert$SALES[advert$AREA == "S"])
meanS

# For northern districts, they spend about $293.9891 thousand on biscuits
# For southern districts, they spend about $316.236 thousand on biscuits


# Q3 (B). PERFORM A PERMUTATION TEST ON THE DIFFERENCE IN MEAN SPENDING 

# Set trials, initialize array, and create temp df
trials <- 500
responses <- numeric(trials)
tmp <- advert
  
for (i in 1:trials) {
  
  # Permute the AREA
  tmp$AREA <- sample(advert$AREA)
  
  # Get the mean value for each trial
  mean_north <- mean(tmp$SALES[tmp$AREA == 'N'])
  mean_south <- mean(tmp$SALES[tmp$AREA == "S"])
  responses[i] <- mean_north - mean_south
}

hist(responses,
     freq = FALSE,
     xlab = "Mean of North - Mean of South",
     ylab = "Percentage",
     main = "Difference in Mean Spending Permutated")


# Q3 (C). HOW DO YOU ANSWER YOUR BOSS' QUESTION?

diff <- meanN - meanS
abline(v = diff, col = "blue", lwd = 2)

abline(v = quantile(responses, c(0.025, 0.975)),
       col = "orange",
       lwd = 2)

legend("topleft",  
       legend = c("95% of differences", "recorded difference"),  
       lwd = 2, 
       col = c("orange", "blue"))

# Since the recorded difference in real life is within the range of 95% of differences,
# We can say that it is not statistically significant of the possibility that
# Southerners like biscuits better than Northerners
# Thus, the rumour is likely to be false